name: Build Review Version
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: ${{ startsWith(github.event.review.body, 'Build review') && github.event.pull_request.base.ref == 'koni-dev' }}
    strategy:
      matrix:
        step: ['android', 'ios']
    name: ${{ matrix.step }}
    runs-on: mac-worker
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: ${{ matrix.step }}
      if: ${{ contains(github.event.review.body, matrix.step) }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        KS_PASSWORD: ${{ secrets.KS_PASSWORD }}
        NEXTCLOUD_CONFIG: ${{ secrets.NEXTCLOUD_CONFIG }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        node ./scripts/run-build.mjs --${{ matrix.step }}
